export const isDesktopOrLaptop = '(min-device-width: 1224px)'
export const isBigScreen = '(min-device-width: 1824px)'
export const isTabletOrMobile = '(max-width: 1224px)'
export const isTabletOrMobileDevice = '(max-device-width: 1224px)'
export const isPortrit = '(orientation: portrait)'
export const isRetina = '(min-resolution: 2dppx)'